export default {
    economics:'md-trending-up',
    maths:'ios-calculator',
    science:'md-beaker',
    humanities:'ios-book',
    pdhpe:'md-football',
    english:'ios-paper',
    dance:"md-musical-notes",
    yoga:"ios-body",
    coding:'md-code-working',
    geography:"md-globe",

    french:'ios-quote',
    spanish:'ios-quote',
    japanese:'ios-quote',
    arabic:'ios-quote',
    german:'ios-quote',
    chinese:'ios-quote',
    indonesian:'ios-quote',
    hindi:'ios-quote',
    greek:'ios-quote',

    guitar:"ios-musical-note",
    piano:"ios-musical-note",
    trumpet:"ios-musical-note",
    trombone:"ios-musical-note",
    baritone:"ios-musical-note",
    cello:"ios-musical-note",
    clarinet:"ios-musical-note",
    doubleBass:"ios-musical-note",
    guitar:"ios-musical-note",
    flute:"ios-musical-note",
    violin:"ios-musical-note",
    viola:"ios-musical-note"
  };